from app import db
from models import Laptop
import logging

def initialize_laptop_data():
    """
    Initialize the database with laptop data if it doesn't already exist.
    This function checks if laptops exist in the database and adds them if not.
    """
    # Check if we already have laptops in the database
    laptop_count = Laptop.query.count()
    if laptop_count > 0:
        logging.info(f"Database already contains {laptop_count} laptops. Skipping initialization.")
        return

    logging.info("Initializing laptop database with sample data...")
    
    # Create a list of realistic laptop data
    laptops = [
        # Budget Gaming Laptops
        Laptop(
            brand="Acer", 
            model="Nitro 5", 
            price=699.99,
            cpu="Intel Core i5-11400H",
            gpu="NVIDIA GeForce GTX 1650",
            ram=8,
            storage_type="SSD",
            storage_capacity=512,
            display_size=15.6,
            display_resolution="1920x1080",
            display_refresh_rate=60,
            weight=2.3,
            battery_life=6.0,
            operating_system="Windows 11",
            cinebench_score=9800,
            geekbench_score=4800,
            gaming_fps=55.0,
            user_rating=4.1,
            build_quality="Average",
            value_category="Budget",
            suitable_for_gaming=True,
            suitable_for_students=True,
            price_performance_ratio=0.78
        ),
        Laptop(
            brand="HP", 
            model="Victus 15", 
            price=749.99,
            cpu="AMD Ryzen 5 5600H",
            gpu="NVIDIA GeForce GTX 1650",
            ram=8,
            storage_type="SSD",
            storage_capacity=512,
            display_size=15.6,
            display_resolution="1920x1080",
            display_refresh_rate=60,
            weight=2.4,
            battery_life=5.5,
            operating_system="Windows 11",
            cinebench_score=10200,
            geekbench_score=5100,
            gaming_fps=58.0,
            user_rating=4.0,
            build_quality="Average",
            value_category="Budget",
            suitable_for_gaming=True,
            suitable_for_students=True,
            price_performance_ratio=0.76
        ),
        
        # Mid-range Gaming Laptops
        Laptop(
            brand="Lenovo", 
            model="Legion 5", 
            price=999.99,
            cpu="AMD Ryzen 7 5800H",
            gpu="NVIDIA GeForce RTX 3060",
            ram=16,
            storage_type="SSD",
            storage_capacity=1000,
            display_size=15.6,
            display_resolution="1920x1080",
            display_refresh_rate=144,
            weight=2.4,
            battery_life=7.0,
            operating_system="Windows 11",
            cinebench_score=13400,
            geekbench_score=7200,
            gaming_fps=95.0,
            user_rating=4.5,
            build_quality="Good",
            value_category="Mid-Range",
            suitable_for_gaming=True,
            suitable_for_content_creation=True,
            price_performance_ratio=0.88
        ),
        Laptop(
            brand="ASUS", 
            model="TUF Gaming A15", 
            price=1049.99,
            cpu="AMD Ryzen 7 6800H",
            gpu="NVIDIA GeForce RTX 3060",
            ram=16,
            storage_type="SSD",
            storage_capacity=512,
            display_size=15.6,
            display_resolution="1920x1080",
            display_refresh_rate=144,
            weight=2.3,
            battery_life=7.5,
            operating_system="Windows 11",
            cinebench_score=13800,
            geekbench_score=7300,
            gaming_fps=98.0,
            user_rating=4.4,
            build_quality="Good",
            value_category="Mid-Range",
            suitable_for_gaming=True,
            suitable_for_content_creation=True,
            price_performance_ratio=0.85
        ),
        
        # High-end Gaming Laptops
        Laptop(
            brand="MSI", 
            model="Stealth 15M", 
            price=1699.99,
            cpu="Intel Core i7-12700H",
            gpu="NVIDIA GeForce RTX 3070 Ti",
            ram=32,
            storage_type="SSD",
            storage_capacity=1000,
            display_size=15.6,
            display_resolution="2560x1440",
            display_refresh_rate=165,
            weight=2.1,
            battery_life=6.0,
            operating_system="Windows 11",
            cinebench_score=15600,
            geekbench_score=9800,
            gaming_fps=140.0,
            user_rating=4.7,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_gaming=True,
            suitable_for_content_creation=True,
            price_performance_ratio=0.82
        ),
        Laptop(
            brand="Razer", 
            model="Blade 15", 
            price=2299.99,
            cpu="Intel Core i9-12900H",
            gpu="NVIDIA GeForce RTX 3080",
            ram=32,
            storage_type="SSD",
            storage_capacity=1000,
            display_size=15.6,
            display_resolution="2560x1440",
            display_refresh_rate=240,
            weight=2.0,
            battery_life=5.5,
            operating_system="Windows 11",
            cinebench_score=17200,
            geekbench_score=10400,
            gaming_fps=165.0,
            user_rating=4.8,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_gaming=True,
            suitable_for_content_creation=True,
            price_performance_ratio=0.72
        ),
        
        # Business Laptops
        Laptop(
            brand="Dell", 
            model="XPS 13", 
            price=1299.99,
            cpu="Intel Core i7-1260P",
            gpu="Intel Iris Xe",
            ram=16,
            storage_type="SSD",
            storage_capacity=512,
            display_size=13.4,
            display_resolution="3840x2400",
            display_refresh_rate=60,
            weight=1.27,
            battery_life=12.0,
            operating_system="Windows 11",
            cinebench_score=10200,
            geekbench_score=5600,
            gaming_fps=25.0,
            user_rating=4.7,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_business=True,
            suitable_for_students=True,
            price_performance_ratio=0.85
        ),
        Laptop(
            brand="Lenovo", 
            model="ThinkPad X1 Carbon", 
            price=1499.99,
            cpu="Intel Core i7-1270P",
            gpu="Intel Iris Xe",
            ram=16,
            storage_type="SSD",
            storage_capacity=1000,
            display_size=14.0,
            display_resolution="1920x1200",
            display_refresh_rate=60,
            weight=1.12,
            battery_life=15.0,
            operating_system="Windows 11",
            cinebench_score=10400,
            geekbench_score=5800,
            gaming_fps=22.0,
            user_rating=4.8,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_business=True,
            price_performance_ratio=0.78
        ),
        
        # Student/Budget Work Laptops
        Laptop(
            brand="Acer", 
            model="Aspire 5", 
            price=549.99,
            cpu="AMD Ryzen 5 5500U",
            gpu="AMD Radeon Graphics",
            ram=8,
            storage_type="SSD",
            storage_capacity=256,
            display_size=15.6,
            display_resolution="1920x1080",
            display_refresh_rate=60,
            weight=1.8,
            battery_life=8.0,
            operating_system="Windows 11",
            cinebench_score=7600,
            geekbench_score=4200,
            gaming_fps=35.0,
            user_rating=4.2,
            build_quality="Good",
            value_category="Budget",
            suitable_for_students=True,
            suitable_for_business=True,
            price_performance_ratio=0.92
        ),
        Laptop(
            brand="HP", 
            model="Pavilion 15", 
            price=599.99,
            cpu="Intel Core i5-1135G7",
            gpu="Intel Iris Xe",
            ram=8,
            storage_type="SSD",
            storage_capacity=512,
            display_size=15.6,
            display_resolution="1920x1080",
            display_refresh_rate=60,
            weight=1.75,
            battery_life=7.5,
            operating_system="Windows 11",
            cinebench_score=7200,
            geekbench_score=4300,
            gaming_fps=30.0,
            user_rating=4.0,
            build_quality="Average",
            value_category="Budget",
            suitable_for_students=True,
            suitable_for_business=True,
            price_performance_ratio=0.88
        ),
        
        # Content Creation Laptops
        Laptop(
            brand="Apple", 
            model="MacBook Pro 14", 
            price=1999.99,
            cpu="Apple M1 Pro",
            gpu="Apple M1 Pro GPU",
            ram=16,
            storage_type="SSD",
            storage_capacity=512,
            display_size=14.2,
            display_resolution="3024x1964",
            display_refresh_rate=120,
            weight=1.6,
            battery_life=17.0,
            operating_system="macOS",
            cinebench_score=12400,
            geekbench_score=12600,
            gaming_fps=60.0,
            user_rating=4.9,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_content_creation=True,
            suitable_for_business=True,
            price_performance_ratio=0.95
        ),
        Laptop(
            brand="ASUS", 
            model="ProArt StudioBook 16", 
            price=1899.99,
            cpu="AMD Ryzen 9 5900HX",
            gpu="NVIDIA GeForce RTX 3070",
            ram=32,
            storage_type="SSD",
            storage_capacity=1000,
            display_size=16.0,
            display_resolution="3840x2400",
            display_refresh_rate=60,
            weight=2.4,
            battery_life=8.0,
            operating_system="Windows 11",
            cinebench_score=16000,
            geekbench_score=9400,
            gaming_fps=110.0,
            user_rating=4.7,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_content_creation=True,
            suitable_for_gaming=True,
            price_performance_ratio=0.88
        ),
        
        # 2-in-1 Laptops
        Laptop(
            brand="Microsoft", 
            model="Surface Pro 9", 
            price=1099.99,
            cpu="Intel Core i5-1235U",
            gpu="Intel Iris Xe",
            ram=8,
            storage_type="SSD",
            storage_capacity=256,
            display_size=13.0,
            display_resolution="2880x1920",
            display_refresh_rate=120,
            weight=0.87,
            battery_life=15.5,
            operating_system="Windows 11",
            cinebench_score=7800,
            geekbench_score=5600,
            gaming_fps=25.0,
            user_rating=4.5,
            build_quality="Excellent",
            value_category="Mid-Range",
            suitable_for_students=True,
            suitable_for_business=True,
            price_performance_ratio=0.82
        ),
        Laptop(
            brand="HP", 
            model="Spectre x360", 
            price=1349.99,
            cpu="Intel Core i7-1255U",
            gpu="Intel Iris Xe",
            ram=16,
            storage_type="SSD",
            storage_capacity=512,
            display_size=13.5,
            display_resolution="3000x2000",
            display_refresh_rate=60,
            weight=1.34,
            battery_life=16.0,
            operating_system="Windows 11",
            cinebench_score=9600,
            geekbench_score=5800,
            gaming_fps=28.0,
            user_rating=4.6,
            build_quality="Excellent",
            value_category="High-End",
            suitable_for_business=True,
            suitable_for_students=True,
            price_performance_ratio=0.84
        ),
        
        # Additional budget options
        Laptop(
            brand="Dell", 
            model="Inspiron 15", 
            price=429.99,
            cpu="Intel Core i3-1115G4",
            gpu="Intel UHD Graphics",
            ram=8,
            storage_type="SSD",
            storage_capacity=256,
            display_size=15.6,
            display_resolution="1366x768",
            display_refresh_rate=60,
            weight=1.8,
            battery_life=6.0,
            operating_system="Windows 11",
            cinebench_score=5200,
            geekbench_score=3600,
            gaming_fps=15.0,
            user_rating=3.8,
            build_quality="Average",
            value_category="Budget",
            suitable_for_students=True,
            price_performance_ratio=0.86
        ),
        Laptop(
            brand="Lenovo", 
            model="IdeaPad 3", 
            price=379.99,
            cpu="AMD Ryzen 3 5300U",
            gpu="AMD Radeon Graphics",
            ram=8,
            storage_type="SSD",
            storage_capacity=256,
            display_size=14.0,
            display_resolution="1920x1080",
            display_refresh_rate=60,
            weight=1.45,
            battery_life=7.0,
            operating_system="Windows 11",
            cinebench_score=5600,
            geekbench_score=3800,
            gaming_fps=18.0,
            user_rating=3.9,
            build_quality="Average",
            value_category="Budget",
            suitable_for_students=True,
            price_performance_ratio=0.95
        )
    ]
    
    # Add all laptops to the database
    db.session.bulk_save_objects(laptops)
    db.session.commit()
    
    logging.info(f"Successfully added {len(laptops)} laptops to the database.")
